In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression

In [3]:
df = pd.read_csv('E:/AIML/ML_linearregression_sample.csv')
df

,direct_net_irridiance,Wind_velocity,ambient_temperature,heat_loss,Outdoor Humidity (%),Absolute Pressure (mmHg),heat_gain
0,4.58114,0.4,30.2,14.85160,79.0,755.9,18.03950
1,3.18834,0.0,30.7,12.74270,80.0,756.2,9.76156
2,3.32113,1.3,31.1,5.29474,81.0,756.3,7.28081
3,3.37828,1.0,30.6,6.23488,NaN,756.3,6.68976
4,1.81527,1.0,31.0,4.16016,82.0,756.3,5.14517
5,2.01655,0.4,30.8,3.94053,84.0,756.2,4.00957
6,2.62564,0.4,31.0,3.74582,83.0,756.4,4.42987
7,3.22008,0.8,31.3,3.82891,83.0,756.4,5.62730
8,2.98386,0.9,31.5,3.76055,83.0,756.2,6.22621

In [5]:
mean_value=df['Outdoor Humidity (%)'].mean()
df['Outdoor Humidity (%)'].fillna(value=mean_value, inplace=True)
df

,direct_net_irridiance,Wind_velocity,ambient_temperature,heat_loss,Outdoor Humidity (%),Absolute Pressure (mmHg),heat_gain
0,4.58114,0.4,30.2,14.85160,79.000,755.9,18.03950
1,3.18834,0.0,30.7,12.74270,80.000,756.2,9.76156
2,3.32113,1.3,31.1,5.29474,81.000,756.3,7.28081
3,3.37828,1.0,30.6,6.23488,81.875,756.3,6.68976
4,1.81527,1.0,31.0,4.16016,82.000,756.3,5.14517
5,2.01655,0.4,30.8,3.94053,84.000,756.2,4.00957
6,2.62564,0.4,31.0,3.74582,83.000,756.4,4.42987
7,3.22008,0.8,31.3,3.82891,83.000,756.4,5.62730
8,2.98386,0.9,31.5,3.76055,83.000,756.2,6.22621

In [7]:
X =df.drop(columns=['heat_gain'])
X

,direct_net_irridiance,Wind_velocity,ambient_temperature,heat_loss,Outdoor Humidity (%),Absolute Pressure (mmHg)
0,4.58114,0.4,30.2,14.85160,79.000,755.9
1,3.18834,0.0,30.7,12.74270,80.000,756.2
2,3.32113,1.3,31.1,5.29474,81.000,756.3
3,3.37828,1.0,30.6,6.23488,81.875,756.3
4,1.81527,1.0,31.0,4.16016,82.000,756.3
5,2.01655,0.4,30.8,3.94053,84.000,756.2
6,2.62564,0.4,31.0,3.74582,83.000,756.4
7,3.22008,0.8,31.3,3.82891,83.000,756.4
8,2.98386,0.9,31.5,3.76055,83.000,756.2

In [8]:
y=df['heat_gain']
y

0    18.03950
1     9.76156
2     7.28081
3     6.68976
4     5.14517
5     4.00957
6     4.42987
7     5.62730
8     6.22621
Name: heat_gain, dtype: float64

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25,random_state=0)
model_LR = LinearRegression().fit(X_train, y_train)
lr = LinearRegression().fit(X_train, y_train)

In [15]:
print("Training set score: {:.2f}".format(lr.score(X_train, y_train)))
print("Test set score: {:.2f}".format(lr.score(X_test, y_test)))

Training set score: 1.00
Test set score: -4.78